### ISSUE TITLE
Move about to home

### ISSUE THREAD

**Issue by Tiger-The-Cat** [darkdarcool/ReplAPI-Docs#3]
Home is kinda blank, and since that is the first page that you see, it should probably have the sample code and about the module. maybe change About to About Us?
I wanted to make a pull request out of this, but there is a bunch of scripts and stuff that I am afraid to break.

**Comment by darkdarcool** [comment]
no, we are planning to put more stuff later with like version there later

**Comment by Tiger-The-Cat** [comment]
Oh okay sry

**Comment by darkdarcool** [comment]
its fine! please leave more of these, you're going to leave on that we need eventually(or someone else needs)
